#ifndef _CLIENT_H
#define _CLIENT_H
#define CLIENT_FEATURES_CHAT      (1<<1)
#define CLIENT_FEATURES_AWARENESS (1<<2)
#define CLIENT_FEATURES_EVENTS    (1<<3)
#define CLIENT_FEATURES_MOVE      (1<<4)
#define CLIENT_FEATURES_ALL       (1<<30)-1
#define CLIENT_STATUS_CONNECTED   1
#define CLIENT_STATUS_ACTIVE(s) ((s & CLIENT_FEATURES_CHAT)||(s&CLIENT_FEATURES_AWARENESS))
#endif
